### PR TITLE
makefile, attributes

### PR DESCRIPTION
**Pull request by OliviaCE**
added gitattributes, and added makefile require for bed

### CODE REVIEW

**Comment by OliviaCE** [comment]
hey @NukeWilliams & @krishpranav I've added git attributes and bsd makefile

**Comment by krishpranav** [comment]
hey @OliviaCE is this require??

**Comment by OliviaCE** [comment]
yes off course git attributes for naming our language & makefile for bsd

**Comment by krishpranav** [comment]
ok that's a great thing

**Comment by NukeWilliams** [comment]
great thing @OliviaCE

**Pull request merged**
